name: Build and publish NuGet package NuGetTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      working-directory: ./NuGetTest
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      working-directory: ./NuGetTest
      run: dotnet pack --configuration Release -p:PackageVersion=1.$(date +"%Y%m%d.%H%M%S")
    - name: Publish to nuget source
      working-directory: ./NuGetTest
      run: dotnet nuget push "bin/Release/*.nupkg" --source "github" --skip-duplicate
